/*
작성자 : 이호준
프로젝트 시작일 : 2024-06-17
*/


-- 회원테이블   
CREATE TABLE MBL_TBL ( 
    MBL_ID             VARCHAR2(20)     NOT NULL,
    MBL_PASSWORD       CHAR(60)         NOT NULL,
    MBL_EMAIL          VARCHAR2(100)    NOT NULL,
    MBL_NAME           VARCHAR2(20)     NOT NULL,
    Mbl_Brith          VARCHAR2(10)     NOT NULL,
    MBL_ZIP_CODE       CHAR(5)          NOT NULL,
    MBL_ADDR           VARCHAR2(100)    NOT NULL,
    MBL_ADDR_DETAIL    VARCHAR2(100)    NOT NULL,
    MBL_PHONE          VARCHAR2(20)     NOT NULL,
    MBL_GENDER         CHAR(1)          NOT NULL,
    MBL_POINT          NUMBER           DEFAULT 0 NOT NULL,
    MBL_REGDATE        DATE DEFAULT SYSDATE,
    MBL_UPDATEDATE     DATE DEFAULT SYSDATE
);

-- PRIMARY KEY 설정
ALTER TABLE MBL_TBL ADD CONSTRAINT pk_MBL_TBL PRIMARY KEY(MBL_ID);

COMMIT;

-- 상품정보 테이블

CREATE TABLE PRODUCT_TBL(
    PRO_NUM        NUMBER               NOT NULL,
    CTG_H_CODE     NUMBER               NOT NULL,
    PRO_NAME       VARCHAR2(50)         NOT NULL,
    PRO_CONTENT    VARCHAR2(4000)       NOT NULL,
    PRO_PRICE      NUMBER               NOT NULL,   
    PRO_AMOUNT     NUMBER               NOT NULL,
    PRO_OPTION     CHAR(1)              NOT NULL,
    PRO_BUY        CHAR(1)              NOT NULL,
    PRO_IMG        VARCHAR2(50)         NOT NULL,
    PRO_REGDATE    DATE DEFAULT SYSDATE NOT NULL,
    PRO_UPDATEDATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE PRODUCT_TBL ADD CONSTRAINT pk_PRODUCT_TBL PRIMARY KEY(PRO_NUM);

ALTER TABLE PRODUCT_TBL ADD CONSTRAINT fk_CTG_H_CODE FOREIGN KEY (CTG_H_CODE) REFERENCES CATEGORY_TBL(CTG_H_CODE);

COMMIT;

-- 카테고리
CREATE TABLE CATEGORY_TBL(
    CTG_H_CODE      NUMBER      NOT NULL,
    CTG_T_CODE      NUMBER,
    CTG_L_CODE      NUMBER,
    CTG_NAME        VARCHAR2(30)
);

ALTER TABLE CATEGORY_TBL ADD CONSTRAINT pk_CATEGORY_TBL PRIMARY KEY(CTG_H_CODE);

COMMIT;

select * from tab;
------------------------24/06/25 테이블 설계완성---------------------------------

-- 장바구니 테이블
CREATE TABLE CART_TBL(
    CAT_NUM             NUMBER          NOT NULL,
    PRO_NUM             NUMBER          NOT NULL,
    MBL_ID              VARCHAR2(20)    NOT NULL,
    CAT_AMOUNT          NUMBER          NOT NULL
);

ALTER TABLE CART_TBL ADD CONSTRAINT pk_CART_TBL PRIMARY KEY(CAT_NUM);

ALTER TABLE CART_TBL ADD CONSTRAINT fk_PRO_NUM FOREIGN KEY (PRO_NUM) REFERENCES PRODUCT_TBL(PRO_NUM);
ALTER TABLE CART_TBL ADD CONSTRAINT fk_MBL_ID FOREIGN KEY (MBL_ID) REFERENCES CATEGORY_TBL(MBL_TBL);


-- 주문내용 테이블(주문자 정보테이블)
CREATE TABLE ORDER_TBL (
    ORD_CODE            NUMBER           NOT NULL,
    MBL_ID              VARCHAR2(20)     NOT NULL,
    ORD_NAME            VARCHAR2(20)     NOT NULL,
    ORD_ZIP_CODE        CHAR(5)          NOT NULL,
    ORD_ADDR            VARCHAR2(100)    NOT NULL,
    ORD_ADDRDETAIL      VARCHAR2(100)    NOT NULL,
    ORD_PHONE           VARCHAR2(20)     NOT NULL,
    ORD_POINT           NUMBER DEFAULT 0 NOT NULL,
    ORD_MEMO            VARCHAR2(100)    NULL,
    ORD_PRICE           NUMBER           NOT NULL
);

ALTER TABLE ORDER_TBL ADD CONSTRAINT pk_ORDER_TBL PRIMARY KEY(ORD_CODE);

ALTER TABLE ORDER_TBL ADD CONSTRAINT fk_MBL_ID FOREIGN KEY (MBL_ID) REFERENCES CATEGORY_TBL(MBL_TBL);


-- 주문상세 테이블(주문 상품)
CREATE TABLE P_ORDER_TBL (
    ORD_CODE                NUMBER           NOT NULL,
    PRO_NUM                 NUMBER           NOT NULL,
    P_ORDER_NAME
    P_ORDER_AMOUNT
    P_ORDER_TOTALPRICE
);









